#!/usr/bin/env bash
set -euo pipefail

# =========================================================================
# Boojy Suite status / progress tracker generator
#
# Regenerates the auto SNAPSHOT block in SUITE_STATUS.md (suite-umbrella
# root, public) by scanning each repo's git + version.
#
#   ./scripts/suite-status.sh                 # writes to ./SUITE_STATUS.md
#   ./scripts/suite-status.sh /path/to/doc.md # override the output location
#   SUITE_STATUS_DOC=/path/to/doc.md ./scripts/suite-status.sh
#
# Only the block between AUTO:START / AUTO:END is rewritten — the hand-kept
# "This Week" list and per-app "Focus" sections are preserved. If the doc
# doesn't exist, it's created from a template with those seeded.
# =========================================================================

cd "$(dirname "$0")/.."                 # suite root (boojy/) — repo subfolders resolve from here
DEFAULT_DOC="./SUITE_STATUS.md"
DOC="${1:-${SUITE_STATUS_DOC:-$DEFAULT_DOC}}"
START="<!-- SUITE-STATUS:AUTO:START -->"
END="<!-- SUITE-STATUS:AUTO:END -->"

# name | path (relative to the suite root).
REPOS=(
  "Boojy Audio (DAW)|boojy-audio"
  "Boojy Design|boojy-design"
  "Boojy Notes|boojy-notes"
  "boojy.org (website)|boojy-web"
  "Boojy Cloud|boojy-cloud"
)

get_version() {
  local p="$1" v
  if [ -f "$p/package.json" ]; then
    v=$(jq -r '.version // empty' "$p/package.json" 2>/dev/null || true)
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  if [ -f "$p/website/package.json" ]; then
    v=$(jq -r '.version // empty' "$p/website/package.json" 2>/dev/null || true)
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  if [ -f "$p/CHANGELOG.md" ]; then
    v=$(grep -m1 -E '^##[[:space:]]+v?[0-9]' "$p/CHANGELOG.md" | sed -E 's/^##[[:space:]]+//; s/[[:space:]].*$//' || true)
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  echo "—"
}

gen_rows() {
  local entry name path ver branch last d30 dirty
  for entry in "${REPOS[@]}"; do
    name="${entry%%|*}"; path="${entry##*|}"
    if [ ! -d "$path/.git" ]; then
      printf '| %s | _not found_ | — | — | — | — |\n' "$name"
      continue
    fi
    ver=$(get_version "$path")
    branch=$(git -C "$path" branch --show-current 2>/dev/null || echo '—')
    last=$(git -C "$path" log -1 --format='%cd · %s' --date=short 2>/dev/null | cut -c1-58 || echo '—')
    d30=$(git -C "$path" log --since='30 days ago' --oneline 2>/dev/null | wc -l | tr -d ' ')
    dirty=$(git -C "$path" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    if [ "$dirty" = "0" ]; then dirty="clean"; else dirty="${dirty} uncommitted"; fi
    printf '| %s | %s | %s | %s | %s | %s |\n' "$name" "$ver" "$branch" "$last" "$d30" "$dirty"
  done
}

TODAY=$(date +%Y-%m-%d)
BLOCK_FILE=$(mktemp)
{
  echo "$START"
  echo "_Auto-generated by \`scripts/suite-status.sh\` on ${TODAY} — don't hand-edit this block; re-run the script._"
  echo
  echo "| App | Version | Branch | Last commit | Commits (30d) | Working tree |"
  echo "|-----|---------|--------|-------------|---------------|--------------|"
  gen_rows
  echo "$END"
} > "$BLOCK_FILE"

# Create the tracker from a template (with seeded human sections) if missing.
if [ ! -f "$DOC" ]; then
  mkdir -p "$(dirname "$DOC")"
  cat > "$DOC" << 'TEMPLATE'
# Boojy Suite — Status & Progress Tracker

> The single home for suite-wide progress. Three parts: an auto **Snapshot** (regenerated by
> `scripts/suite-status.sh`), the **This Week** list (disposable — rewritten each Sunday via the
> `/weekly` ritual; no carry-over archive), and per-app **Focus** notes. Targets are one-line
> pointers — detail lives in each repo's `dreams.md`. Strategy/intent lives in `VISION.md`;
> this is operational state, not strategy.

## Snapshot

<!-- SUITE-STATUS:AUTO:START -->
<!-- SUITE-STATUS:AUTO:END -->

## This Week — w/c YYYY-MM-DD

> 3–6 one-line targets, app-prefixed. Wiped and rewritten each Sunday by `/weekly`.

- [ ] _seed targets here_

## Focus — per app (hand-maintained)

> The Snapshot gives the facts; this gives the judgment. Update as priorities move.
TEMPLATE
fi

# Replace the region between the markers with the freshly generated snapshot.
TMP=$(mktemp)
awk -v s="$START" -v e="$END" -v bf="$BLOCK_FILE" '
  index($0, s) { while ((getline line < bf) > 0) print line; close(bf); skip=1; next }
  index($0, e) { skip=0; next }
  !skip { print }
' "$DOC" > "$TMP" && cat "$TMP" > "$DOC"
rm -f "$TMP" "$BLOCK_FILE"

echo "✅ Updated $DOC"
